# Generated by Django 4.2.4 on 2023-10-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_lab1', '0002_audiences'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('moderator', models.IntegerField()),
                ('date_confirmed', models.DateTimeField()),
                ('date_in_progress', models.DateTimeField()),
                ('creater', models.IntegerField()),
                ('date_booling', models.DateTimeField()),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Бронивание',
                'verbose_name_plural': 'Бронирования',
                'db_table': 'booking_requests',
                'managed': False,
            },
        ),
    ]
